# Generated by Django 4.0.2 on 2022-02-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='pics')),
                ('price', models.IntegerField()),
                ('stock', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('offer', models.FloatField()),
                ('offer_offer2', models.BooleanField(default=False)),
            ],
        ),
    ]
